name: Pull Request - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x

    - name: go build
      run: go build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45.2

